- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azrmp-conn'
    subscriptionId: '621f8443-9352-4e05-9162-644d6a579445'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azurermp'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureRmP -linkedTemplateUri https://raw.githubusercontent.com/ImpulseTechnovation/AzureRmP/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'dptdeployment'